version: '3.7'
services:
  ocp-installer:
    build: .
    image: ocp-installer:3.11.
    container_name: ocp-installer
    hostname: ocp-installer
    restart: always
    network_mode: bridge
    dns:
      - 8.8.8.8
    ports:
      - 80:80
    volumes: 
      - ${HOME}/ocp-installer/sharedfolder:/home/ocp1450/sharedfolder