---
- hosts: localhost
  vars:
    HTTP_PROXY: ""
    HTTPS_PROXY: ""
    NO_PROXY: ""
    DNSSERVER_IP: 8.8.8.8
    OCP_INSTALLER_BASTION_NAME: installer
    OCP_WEBSERVER_IP: 10.10.10.10
    BASE_DOMAIN: jdhlabs.com.br
    OCP_VERSION: "4"
    OCP_VERSION_RELEASE: "4"
    OCP_USERID: 1450
    BOOTSTRAP_NAME: bootstrap
    MASTERS_DNS_NAMES: "master-0 master-1 master-2"
    ETCD_DNS_NAMES: "etcd-0 etcd-1 etcd-2"
    INFRA_NODES_DNS_NAMES: "worker-0 worker-1"
    APP_NODES_DNS_NAMES: "worker-2 worker-3"
    WORKERS_REPLICS: 4
    MASTER_REPLICS: 3
    isNodesWithDHCP: "false"
    CLUSTER_ID: ocp
    CLUSTER_CIDR: "10.254.0.0/16"
    CLUSTER_SERVICE_NETWORK: "172.30.0.0/16"
    TIER: bare
    VCENTER_SERVER: vcenter.local
    VCENTER_USER: admin@vmware.local
    VCENTER_PASS: 1q2w3e
    VCENTER_DC: datacenter
    VCENTER_DS: datastore
    PULL_SECRET: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K2pvbmFzY2F2YWxjYW50aWdvbGRlbnRlY2hub2xvZ2lhY29tYnIxcmp1NzJqeHl0dDY3cGRhcGRpa3JhNmtnOWI6NjlTQ0NGQklWQTY2Tk1BTjBEVUdaTjIxUU5OSERKQVgzSU5ER0dDQlpPV1hINDlGNEg2MTJHRExUWDlONjJRMQ==","email":"jonas.cavalcanti@goldentechnologia.com.br"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K2pvbmFzY2F2YWxjYW50aWdvbGRlbnRlY2hub2xvZ2lhY29tYnIxcmp1NzJqeHl0dDY3cGRhcGRpa3JhNmtnOWI6NjlTQ0NGQklWQTY2Tk1BTjBEVUdaTjIxUU5OSERKQVgzSU5ER0dDQlpPV1hINDlGNEg2MTJHRExUWDlONjJRMQ==","email":"jonas.cavalcanti@goldentechnologia.com.br"},"registry.connect.redhat.com":{"auth":"NTI4OTA4MjZ8dWhjLTFSanU3Mkp4WVRUNjdwZGFwRGlrckE2a0c5YjpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmtaREF4TnpFeU1HUm1OVEEwTURBM09EZGxPVFk0WldJNU16TTVaR1kyTnlKOS5SRlU0Mk56QkdYaGp1UFl1cmNLN0ZiMU9UMVFBZ2g4d3BQc2hKYkNobFBwMS1fMVI0M3pnVFFyaXVqUkQ2TDdjczRhNk1HLVhxTjVILUpIVnlKTGhYUG54S2JiVmtXZjlEc1pGM0ZKTnplUEtGeDZjWVVVQUFnUTFjcmtEcWlTemp5R05LOGhOUGRSQk5XREFqZjBQX2l5WFFsUklvRmdPNVgzMlhaV05SRnNfeVJrbC03X0VBNXlMYndSUGhSRTE2Q2QwbGVlNHM3bU44TWdwRUhfWlhCRW90YmpkQ2ttR3Q1TmhRMmUzeUlYOTJJRmcweW54TUZjMHJqLXdaZlRSX2U3eEktb0VUbjlLQjRzdlFiMmNoZDdoc3BTRUZhZXZoY0xCYVBGRkYyeFNwMklwZzRTcWVuTmstaU5lakx1c29vcWR4UlBQYTFkWWJobnJRTmE0dFNzcHc3OWNxYVRsNzhudlZfVXl5SDJ3LXBBcjRXN245bGxHZWdidm1VNHI3Z3d1NjE4TGdIcjZaYnc4MWE2T01lVnBtRU5QckVYOFFpMVdPel9Bemx4dmRjRFd5N3JNTEtVLU91ZUZiMFRLRl82UlF2c2lDdjhDNmp1SlNSYzJHUjZKNU9OWDJ5UTFuWURlSGFkekE5YWhKNWRINlR2T0FxNHFtNElHb28zYnJfV2E5MmZSRE1iOTRHakZqbWdoamFWbGU2aC15R3pBZE55b1NDaENMU25adG93M1Q4M2ZIT3hWczVzRFhzS0h3TGprZXQ2dU5nNU9uSnhHenMzTWFSdXVJeTdkbnRjU2Rxd2JvS1RWUDhIaDJyRk1fVVpPUFlNTHNGeEZteEh3cTJ0NnA0QTlxLWlOUzlwNlp1cUFiU2ZSdE5qNWdQZzhIQmpOMG5BRndldw==","email":"jonas.cavalcanti@goldentechnologia.com.br"},"registry.redhat.io":{"auth":"NTI4OTA4MjZ8dWhjLTFSanU3Mkp4WVRUNjdwZGFwRGlrckE2a0c5YjpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmtaREF4TnpFeU1HUm1OVEEwTURBM09EZGxPVFk0WldJNU16TTVaR1kyTnlKOS5SRlU0Mk56QkdYaGp1UFl1cmNLN0ZiMU9UMVFBZ2g4d3BQc2hKYkNobFBwMS1fMVI0M3pnVFFyaXVqUkQ2TDdjczRhNk1HLVhxTjVILUpIVnlKTGhYUG54S2JiVmtXZjlEc1pGM0ZKTnplUEtGeDZjWVVVQUFnUTFjcmtEcWlTemp5R05LOGhOUGRSQk5XREFqZjBQX2l5WFFsUklvRmdPNVgzMlhaV05SRnNfeVJrbC03X0VBNXlMYndSUGhSRTE2Q2QwbGVlNHM3bU44TWdwRUhfWlhCRW90YmpkQ2ttR3Q1TmhRMmUzeUlYOTJJRmcweW54TUZjMHJqLXdaZlRSX2U3eEktb0VUbjlLQjRzdlFiMmNoZDdoc3BTRUZhZXZoY0xCYVBGRkYyeFNwMklwZzRTcWVuTmstaU5lakx1c29vcWR4UlBQYTFkWWJobnJRTmE0dFNzcHc3OWNxYVRsNzhudlZfVXl5SDJ3LXBBcjRXN245bGxHZWdidm1VNHI3Z3d1NjE4TGdIcjZaYnc4MWE2T01lVnBtRU5QckVYOFFpMVdPel9Bemx4dmRjRFd5N3JNTEtVLU91ZUZiMFRLRl82UlF2c2lDdjhDNmp1SlNSYzJHUjZKNU9OWDJ5UTFuWURlSGFkekE5YWhKNWRINlR2T0FxNHFtNElHb28zYnJfV2E5MmZSRE1iOTRHakZqbWdoamFWbGU2aC15R3pBZE55b1NDaENMU25adG93M1Q4M2ZIT3hWczVzRFhzS0h3TGprZXQ2dU5nNU9uSnhHenMzTWFSdXVJeTdkbnRjU2Rxd2JvS1RWUDhIaDJyRk1fVVpPUFlNTHNGeEZteEh3cTJ0NnA0QTlxLWlOUzlwNlp1cUFiU2ZSdE5qNWdQZzhIQmpOMG5BRndldw==","email":"jonas.cavalcanti@goldentechnologia.com.br"}}}'
    rh_user: 'jonas.cavalcanti@goldentechnologia.com.br'

  vars_prompt:
  - name: rh_password
    prompt: "Your Subscription Password:"
    private: yes

  tasks:
    - name: Setting docker login on registry.redhat.io
      shell: docker login -u {{ rh_user }} -p {{ rh_password }} registry.redhat.io
      #environment:
        #http_proxy: <your proxy server>
    
    - name: Pulling image registry.redhat.io registry.redhat.io/rhel7
      shell: docker pull registry.redhat.io/rhel7:latest
      #environment:
        #http_proxy: <your proxy server>

    - name: Creating Dockerfile
      template: 
        src: ./ansible/confs/Dockerfile.j2
        dest: ./Dockerfile
        mode: "0755"

    - name: Creating docker-compose file
      template: 
        src: ./ansible/confs/docker-compose.j2
        dest: ./docker-compose.yaml
        mode: "0755"

    - name: Creating supervisord.conf file
      template: 
        src: ./ansible/confs/supervisord.j2
        dest: ./confs/supervisord.conf
        mode: "0755"

    - name: Creating vSphere install-config.yaml file
      template: 
        src: ./ansible/playbooks/ocp4/install-config-vsphere.j2
        dest: ./ansible/playbooks/ocp4/install-config-vsphere.yaml
        mode: "0755"

    - name: Creating Bare Metal install-config.yaml file
      template: 
        src: ./ansible/playbooks/ocp4/install-config-bare.j2
        dest: ./ansible/playbooks/ocp4/install-config-bare.yaml
        mode: "0755"   
