---
- hosts: localhost
  vars:
    BASE_DOMAIN: jdhlab.corp
    OCP_USERID: 3900
    OCP_BOOTSTRAP_IGN_DNSNAME: bootstrap
    WORKERS_REPLICS: 4
    WORKERS_DNS_NAMES: "worker1 worker2 worker3 worker4"
    MASTER_REPLICS: 3
    MASTERS_DNS_NAMES: "master-0 master-1 master-2"
    ETCD_DNS_NAMES: "etcd-0 etcd-1 etcd-2"
    CLUSTER_NAME: ocp
    CLUSTER_CIDR: "10.254.0.0/16"
    CLUSTER_SERVICE_NETWORK: "172.30.0.0/16"
    TIER: vsphere
    VCENTER_SERVER: vcenter.local
    VCENTER_USER: admin@vmware.local
    VCENTER_PASS: 1q2w3e
    VCENTER_DC: datacenter
    VCENTER_DS: datastore
    PULL_SECRET: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K2pvbmFzY2F2YWxjYW50aWdvbGRlbnRlY2hub2xvZ2lhY29tYnIxcmp1NzJqeHl0dDY3cGRhcGRpa3JhNmtnOWI6NjlTQ0NGQklWQTY2Tk1BTjBEVUdaTjIxUU5OSERKQVgzSU5ER0dDQlpPV1hINDlGNEg2MTJHRExUWDlONjJRMQ==","email":"jonas.cavalcanti@goldentechnologia.com.br"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K2pvbmFzY2F2YWxjYW50aWdvbGRlbnRlY2hub2xvZ2lhY29tYnIxcmp1NzJqeHl0dDY3cGRhcGRpa3JhNmtnOWI6NjlTQ0NGQklWQTY2Tk1BTjBEVUdaTjIxUU5OSERKQVgzSU5ER0dDQlpPV1hINDlGNEg2MTJHRExUWDlONjJRMQ==","email":"jonas.cavalcanti@goldentechnologia.com.br"},"registry.connect.redhat.com":{"auth":"NTI4OTA4MjZ8dWhjLTFSanU3Mkp4WVRUNjdwZGFwRGlrckE2a0c5YjpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmtaREF4TnpFeU1HUm1OVEEwTURBM09EZGxPVFk0WldJNU16TTVaR1kyTnlKOS5SRlU0Mk56QkdYaGp1UFl1cmNLN0ZiMU9UMVFBZ2g4d3BQc2hKYkNobFBwMS1fMVI0M3pnVFFyaXVqUkQ2TDdjczRhNk1HLVhxTjVILUpIVnlKTGhYUG54S2JiVmtXZjlEc1pGM0ZKTnplUEtGeDZjWVVVQUFnUTFjcmtEcWlTemp5R05LOGhOUGRSQk5XREFqZjBQX2l5WFFsUklvRmdPNVgzMlhaV05SRnNfeVJrbC03X0VBNXlMYndSUGhSRTE2Q2QwbGVlNHM3bU44TWdwRUhfWlhCRW90YmpkQ2ttR3Q1TmhRMmUzeUlYOTJJRmcweW54TUZjMHJqLXdaZlRSX2U3eEktb0VUbjlLQjRzdlFiMmNoZDdoc3BTRUZhZXZoY0xCYVBGRkYyeFNwMklwZzRTcWVuTmstaU5lakx1c29vcWR4UlBQYTFkWWJobnJRTmE0dFNzcHc3OWNxYVRsNzhudlZfVXl5SDJ3LXBBcjRXN245bGxHZWdidm1VNHI3Z3d1NjE4TGdIcjZaYnc4MWE2T01lVnBtRU5QckVYOFFpMVdPel9Bemx4dmRjRFd5N3JNTEtVLU91ZUZiMFRLRl82UlF2c2lDdjhDNmp1SlNSYzJHUjZKNU9OWDJ5UTFuWURlSGFkekE5YWhKNWRINlR2T0FxNHFtNElHb28zYnJfV2E5MmZSRE1iOTRHakZqbWdoamFWbGU2aC15R3pBZE55b1NDaENMU25adG93M1Q4M2ZIT3hWczVzRFhzS0h3TGprZXQ2dU5nNU9uSnhHenMzTWFSdXVJeTdkbnRjU2Rxd2JvS1RWUDhIaDJyRk1fVVpPUFlNTHNGeEZteEh3cTJ0NnA0QTlxLWlOUzlwNlp1cUFiU2ZSdE5qNWdQZzhIQmpOMG5BRndldw==","email":"jonas.cavalcanti@goldentechnologia.com.br"},"registry.redhat.io":{"auth":"NTI4OTA4MjZ8dWhjLTFSanU3Mkp4WVRUNjdwZGFwRGlrckE2a0c5YjpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmtaREF4TnpFeU1HUm1OVEEwTURBM09EZGxPVFk0WldJNU16TTVaR1kyTnlKOS5SRlU0Mk56QkdYaGp1UFl1cmNLN0ZiMU9UMVFBZ2g4d3BQc2hKYkNobFBwMS1fMVI0M3pnVFFyaXVqUkQ2TDdjczRhNk1HLVhxTjVILUpIVnlKTGhYUG54S2JiVmtXZjlEc1pGM0ZKTnplUEtGeDZjWVVVQUFnUTFjcmtEcWlTemp5R05LOGhOUGRSQk5XREFqZjBQX2l5WFFsUklvRmdPNVgzMlhaV05SRnNfeVJrbC03X0VBNXlMYndSUGhSRTE2Q2QwbGVlNHM3bU44TWdwRUhfWlhCRW90YmpkQ2ttR3Q1TmhRMmUzeUlYOTJJRmcweW54TUZjMHJqLXdaZlRSX2U3eEktb0VUbjlLQjRzdlFiMmNoZDdoc3BTRUZhZXZoY0xCYVBGRkYyeFNwMklwZzRTcWVuTmstaU5lakx1c29vcWR4UlBQYTFkWWJobnJRTmE0dFNzcHc3OWNxYVRsNzhudlZfVXl5SDJ3LXBBcjRXN245bGxHZWdidm1VNHI3Z3d1NjE4TGdIcjZaYnc4MWE2T01lVnBtRU5QckVYOFFpMVdPel9Bemx4dmRjRFd5N3JNTEtVLU91ZUZiMFRLRl82UlF2c2lDdjhDNmp1SlNSYzJHUjZKNU9OWDJ5UTFuWURlSGFkekE5YWhKNWRINlR2T0FxNHFtNElHb28zYnJfV2E5MmZSRE1iOTRHakZqbWdoamFWbGU2aC15R3pBZE55b1NDaENMU25adG93M1Q4M2ZIT3hWczVzRFhzS0h3TGprZXQ2dU5nNU9uSnhHenMzTWFSdXVJeTdkbnRjU2Rxd2JvS1RWUDhIaDJyRk1fVVpPUFlNTHNGeEZteEh3cTJ0NnA0QTlxLWlOUzlwNlp1cUFiU2ZSdE5qNWdQZzhIQmpOMG5BRndldw==","email":"jonas.cavalcanti@goldentechnologia.com.br"}}}'
    OCP_SSH_KEY: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCwYJ7n17NSKgF4stmxnRUVOVF2oqlucSb192Cz1vwbdRcnQMIyKGv8oJTnM6B9THi4OzAEHS5/JTUe0yhnlIoPe47Dz1n6XL4zMExF93C8NwIhnP2VDjp8W4cU+ArEi7GD4hUSUt20eSjPscPJ/mI+MN1mDnPM94XzVcfb/icBhBq43vM/lLywEsUgvG1zkg3ZEVQT13eZ0iHG3L3kvuDtGSAuB0FOAXu0vdzZS4tDtT/fQ7oMNPXIpBRWdJ3iZjw2ZAQ+mr6LV9ioTvCLAeezOCWwELH9N5LBsu5mbw9O0etgfbGOR9JL2Kiy+ss4xJ8jMABSppDli8eofer1RK4gnESqvaqFzkDnGlqHN6j2HwJI21KWcWKyieQ/xPTSufmWfgsvpIxbHvbj+FJaILoUKPNuc3IoL3PS8gbejgEz+5ybKdFu/YsY8QyIHe55+zUvZhiue+Y9sgKfS/0l4FjHHg+X2sBUsQR4hR+ntmq+HnW6Y8kPwywrTTfy5YdIIUoig7U4rnzqKYbq3gvgLWdzkyOQV02Uk+ZJOuKsuNFtEHCMsATVMPzZY1tNST0C5htShvB1VzOjGUROJfCik16nQPLZXZ8RXVnHGFnxyKUmgJXBRcLRPyPVJiKkz8tEQ137KXC4NJpxAzoRlL6W8IwPjw4H2a8MTZZTM9vFjDsRrQ== initiator@ocp-bootstrap-ignition'
  tasks:
    - name: Creating Dockerfile
      template: 
        src: ./playbooks/Dockerfile.j2
        dest: ./Dockerfile
        mode: "0755"
    - name: Creating docker-compose file
      template: 
        src: ./playbooks/docker-compose.j2
        dest: ./docker-compose.yaml
        mode: "0755"
    - name: Creating install-config.yaml file
      template: 
        src: ./playbooks/install-config.j2
        dest: ./confs/install-config.yaml
        mode: "0755"
    - name: Creating supervisord.conf file
      template: 
        src: ./playbooks/supervisord.j2
        dest: ./confs/supervisord.conf
        mode: "0755"
