---
- hosts:
    - masters
    - infras
    - appnodes
    
  vars:
      rh_user: 'jonas.cavalcanti@goldentechnologia.com.br'
    
  vars_prompt:
    - name: rh_password
      prompt: "Your Subscription Password:"
      private: yes
      
  tasks:
    - name: SET RHEL Subscriptions on Nodes
      redhat_subscription:
        state: present
        username: "{{ rh_user }}"
        password: "{{ rh_password }}"
        auto_attach: true
  
    - name: Pull the latest subscription data from RHSM
      command: "subscription-manager refresh"

