---
- hosts:
    - bastion

  vars:
    rhelpkgs: [rhel-7-server-ose-3.11-rpms]

  tasks:
    - name: Active Openshift Repositories
      command: "subscription-manager repos --enable={{ item }}"
      with_items:
        - "{{ ocppkgs }}"