- hosts: masters
  tasks:
    - name: Subscribe Masters Nodes
      shell: 'subscription-manager attach --pool={{master_pool}}'

- hosts: infras
  tasks:
    - name: Subscribe Infras Nodes
      shell: 'subscription-manager attach --pool={{infra_pool}}'

- hosts: appnodes
  tasks:
    - name: Subscribe App Nodes
      shell: 'subscription-manager attach --pool={{app_pool}}'