---
- hosts: 
    - masters
    - workers 
    
  vars:
    docker_version: "docker"
    stor_drv: "overlay2"
    devs: "/dev/sdc"
    docker_cidr: "10.252.0.1/24"

  tasks:
    - name: Clean all Repositories and make repolist
      shell: yum clean all && yum repolist

    - name: Configure Selinux Policy
      selinux:
        policy: targeted
        state: enforcing

    - name: Install Required Packages
      yum: name={{ item }} state=installed
      with_items:
        - wget
        - git
        - net-tools
        - bind-utils
        - iptables-services
        - bridge-utils
        - bash-completion
        - kexec-tools
        - sos
        - psacct
        - yum-utils

    - name: Insert/Update NM_CONTROLLED and PEERDNS
      blockinfile:
        path: /etc/sysconfig/network-scripts/ifcfg-{{ ansible_default_ipv4.interface }}
        block: |
          NM_CONTROLLED=yes
          PEERDNS=yes

    - name: Install Network Manager
      yum:
        name: NetworkManager
        state:  latest

    - name: Enable Network Manager
      service: name=NetworkManager enabled=true state=started

    - name: Setting swap to off
      blockinfile:
        path: /etc/bashrc
        block: |
          swapoff -a

    - name: Diable swap on OS
      command: swapoff -a 
      
    - name: Enable Firewall
      service:
        name: firewalld 
        state: started 
        enabled: "true"

    - name: Installing {{ docker_version }}
      become: true
      yum:
        name: "{{ docker_version }}"
        state: latest

    - name: Update the System
      yum: state=latest name='*'

    - name: Configure Selinux Policy
      selinux:
        policy: targeted
        state: enforcing

    - name: Stop Docker Service
      service:
        name: docker
        state: stopped

    - name: Wipe Docker Device
      shell: wipefs -af {{devs}}

    - name: Remove Docker Content from /var/lib/docker
      command: rm -rf /var/lib/docker/*

    - name: Remove Docker Storage File if exist
      command: rm -rf /etc/sysconfig/docker-storage-setup

    - name: Configure Docker Storage File
      copy:
        content: "STORAGE_DRIVER={{ stor_drv }}\nDEVS={{devs}}\nVG=docker-vg\nCONTAINER_ROOT_LV_NAME=docker-lv\nCONTAINER_ROOT_LV_SIZE=100%FREE\nDATA_SIZE=100%FREE\nCONTAINER_ROOT_LV_MOUNT_PATH=/var/lib/docker"
        dest: "/etc/sysconfig/docker-storage-setup"

    - name: Setup Docker Storage
      command: docker-storage-setup

    - name: Create file daemon.json to change docker0 interface IP
      become: true  
      copy:
        content: '{ "bip": "{{ docker_cidr }}" }'
        dest: "/etc/docker/daemon.json"

    - name: Enable and Start Docker Service
      service:
        name: docker
        state: started
        enabled: yes