apiVersion: v1
kind: PersistentVolume
metadata:
  name: system-redis-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: <nfs.domain>
    path: "<path>"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: <nfs.domain>
    path: "<path>"
 
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: system-storage
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: <nfs.domain>
    path: "<path>"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-redis-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: <nfs.domain>
    path: "<path>"