apiVersion: v1
kind: PersistentVolume
metadata:
  name: system-redis-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.6.65.112
    path: "/mnt/system-redis-storage"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.6.65.112
    path: "/mnt/mysql-storage"
 
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: system-storage
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.6.65.112
    path: "/mnt/system-storage"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-redis-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.6.65.112
    path: "/mnt/backend-redis-storage"