---
- hosts: 
    - masters

  vars:
    docker_version: ""
    stor_drv: "overlay2"
    docker_cidr: "10.252.0.1/16"

  tasks:
    - name: Installing Docker on Master
      yum:
        name: 
          - docker
        state: installed
    
    - name: Stop Docker Service
      service:
        name: docker
        state: stopped
    
    # - name: Wipe Docker Device
    #   shell: wipefs -af {{devs}}

    - name: Remove Docker Content from /var/lib/docker
      command: rm -rf /var/lib/docker/*

    - name: Remove Docker Storage File if exist
      command: rm -rf /etc/sysconfig/docker-storage-setup

    - name: Creating CNI path /etc/cni/net.d/
      command: mkdir -p /etc/cni/net.d/

    - name: 'Setting Openshift Network on /etc/cni/net.d/80-openshift-network.conf'
      copy:
        content: '{ "cniVersion": "0.2.0", "name": "openshift-sdn", "type": "openshift-sdn" }'
        dest: "/etc/cni/net.d/80-openshift-network.conf"

    # - name: Configure Docker Storage File
    #   copy:
    #     content: "STORAGE_DRIVER={{ stor_drv }}\nDEVS={{devs}}\nVG=docker-vg\nCONTAINER_ROOT_LV_NAME=docker-lv\nCONTAINER_ROOT_LV_SIZE=100%FREE\nDATA_SIZE=100%FREE\nCONTAINER_ROOT_LV_MOUNT_PATH=/var/lib/docker"
    #     dest: "/etc/sysconfig/docker-storage-setup"

    # - name: Setup Docker Storage
    #   command: docker-storage-setup

    - name: Create file daemon.json to change docker0 interface IP
      become: true  
      copy:
        content: '{ "bip": "{{ docker_cidr }}" }'
        dest: "/etc/docker/daemon.json"

    - name: Enable and Start Docker Service
      service:
        name: docker
        state: started
        enabled: yes